/**
 * The Gemma BPE tokenizer, as much of it as SigLIP 2 text queries need.
 *
 * **This is BPE with byte fallback, not sentencepiece Unigram.** The plan's §4.1
 * and an early draft of `vision-model-choice.md` both assumed Unigram and Viterbi
 * segmentation; `tokenizer.json` says otherwise, and it is the authority. What is
 * implemented here is exactly what that file declares:
 *
 *   1. **normalizer** — `Replace(" " → "▁")`. Note there is no `Lowercase`, and
 *      no prefix space. `do_lower_case: true` in `tokenizer_config.json` is a
 *      legacy field the fast tokenizer ignores, which is why `Alice` and `ALICE`
 *      tokenize differently and why nothing here folds case. Verified against the
 *      reference implementation — see `vision-tokenizer.test.ts`.
 *   2. **pre_tokenizer** — `Split(" ")`, which is a no-op after step 1 has
 *      removed every space. So BPE runs over the whole normalized string at once,
 *      rather than word by word.
 *   3. **model** — BPE, 256 k vocab, 580 k ranked merges, `byte_fallback: true`.
 *   4. **post_processor** — append `<eos>`.
 *   5. **padding** — to exactly 64 with `<pad>`, which is fixed rather than a
 *      maximum: SigLIP was trained at that length.
 *
 * Why hand-written rather than a dependency: `onnxruntime-node` is already the
 * one heavyweight thing the engine may load, and a tokenizer library would be a
 * second native dependency reachable from the query worker for ~150 lines of
 * well-specified string handling. The risk in doing it by hand is a *subtly*
 * wrong encoding, which silently degrades every query rather than failing — so
 * the test pins token ids against vectors generated by HuggingFace's own
 * `tokenizers`, which is the only thing that actually rules that out.
 *
 * No ONNX here. Safe to import from anywhere, including tests.
 */

import { readFileSync } from "node:fs";
import { SEARCH_EOS_ID, SEARCH_PAD_ID, SEARCH_TEXT_TOKENS } from "../models";

/**
 * Separator for the merge-rank key.
 *
 * NUL rather than a space, because it cannot occur in a vocabulary piece —
 * `tokenizer.json`'s own space-joined merge format relies on the normalizer having
 * already turned every space into `\u2581`, and borrowing that assumption for our
 * lookup key would be relying on it twice.
 *
 * Written as an escape rather than a literal byte: a literal NUL makes git treat
 * this file as binary, which costs every future diff and review of it.
 */
const MERGE_SEP = "\u0000";

/** The subset of `tokenizer.json` this needs. */
interface TokenizerFile {
  model: {
    type: string;
    vocab: Record<string, number>;
    merges: Array<[string, string] | string>;
    byte_fallback?: boolean;
  };
}

export class GemmaTokenizer {
  private constructor(
    private readonly vocab: Map<string, number>,
    /** `left + MERGE_SEP + right` → merge rank. Lower wins. */
    private readonly ranks: Map<string, number>,
    private readonly byteFallback: boolean,
  ) {}

  /**
   * Parse a `tokenizer.json`.
   *
   * ~34 MB of JSON and ~840 k map entries, which is why the query worker holds
   * one of these for its lifetime rather than building one per search.
   */
  static fromFile(path: string): GemmaTokenizer {
    const parsed = JSON.parse(readFileSync(path, "utf-8")) as TokenizerFile;
    if (parsed.model?.type !== "BPE") {
      throw new Error(`expected a BPE tokenizer, got ${parsed.model?.type ?? "nothing"}`);
    }

    const vocab = new Map<string, number>(Object.entries(parsed.model.vocab));
    const ranks = new Map<string, number>();
    parsed.model.merges.forEach((merge, rank) => {
      // Newer `tokenizer.json` files store merges as `[left, right]`; older ones
      // as a single space-joined string. Both appear in the wild for this repo's
      // lineage, so both are accepted rather than assumed.
      const [left, right] = Array.isArray(merge) ? merge : splitOnce(merge);
      ranks.set(left + MERGE_SEP + right, rank);
    });

    return new GemmaTokenizer(vocab, ranks, parsed.model.byte_fallback ?? false);
  }

  get vocabSize(): number {
    return this.vocab.size;
  }

  /**
   * `text` → the fixed-length id tensor the text tower takes.
   *
   * Always `SEARCH_TEXT_TOKENS` long. Sequences longer than that are truncated to
   * leave room for `<eos>`, because a query that loses its terminator is a
   * different input than the tower was trained on.
   */
  encode(text: string): Int32Array {
    const ids = this.encodeTokens(text);
    const out = new Int32Array(SEARCH_TEXT_TOKENS).fill(SEARCH_PAD_ID);
    const keep = Math.min(ids.length, SEARCH_TEXT_TOKENS - 1);
    for (let i = 0; i < keep; i++) out[i] = ids[i];
    out[keep] = SEARCH_EOS_ID;
    return out;
  }

  /** The ids for `text` alone — no `<eos>`, no padding. Exposed for tests. */
  encodeTokens(text: string): number[] {
    if (text.length === 0) return [];
    // Step 1: the only normalization there is. Every space becomes `▁`, and
    // nothing else changes — not the case, not the punctuation.
    const normalized = text.replaceAll(" ", "▁");
    // Step 2 is a no-op by construction (nothing left to split on), so BPE runs
    // over the whole string.
    return this.bpe([...normalized]).flatMap((symbol) => this.idsFor(symbol));
  }

  /**
   * Merge the highest-ranked adjacent pair until none is left.
   *
   * O(n²) in the number of symbols, which is the straightforward formulation and
   * entirely adequate here: `n` is the character count of a search query, not a
   * document. A priority queue would be the same answer, slower to read.
   */
  private bpe(symbols: string[]): string[] {
    if (symbols.length < 2) return symbols;
    const parts = [...symbols];
    for (;;) {
      let bestRank = Infinity;
      let bestAt = -1;
      for (let i = 0; i < parts.length - 1; i++) {
        const rank = this.ranks.get(parts[i] + MERGE_SEP + parts[i + 1]);
        if (rank !== undefined && rank < bestRank) {
          bestRank = rank;
          bestAt = i;
        }
      }
      if (bestAt < 0) return parts;
      parts.splice(bestAt, 2, parts[bestAt] + parts[bestAt + 1]);
      if (parts.length === 1) return parts;
    }
  }

  /**
   * A merged symbol → one or more ids.
   *
   * Normally one lookup. When a symbol is not in the vocabulary at all —
   * an unusual glyph, an unassigned code point — `byte_fallback` spells it as its
   * UTF-8 bytes via the `<0xXX>` tokens, which is what keeps an exotic query from
   * collapsing to `<unk>` and embedding as noise.
   */
  private idsFor(symbol: string): number[] {
    const direct = this.vocab.get(symbol);
    if (direct !== undefined) return [direct];

    if (this.byteFallback) {
      const ids: number[] = [];
      for (const byte of Buffer.from(symbol, "utf-8")) {
        const hex = `<0x${byte.toString(16).toUpperCase().padStart(2, "0")}>`;
        const id = this.vocab.get(hex);
        // A vocabulary declaring `byte_fallback` contains all 256; if one is
        // missing the file is not what it claims, and silently dropping bytes
        // would be worse than saying so.
        if (id === undefined) throw new Error(`byte fallback token ${hex} missing from vocab`);
        ids.push(id);
      }
      return ids;
    }

    const unk = this.vocab.get("<unk>");
    if (unk === undefined) throw new Error(`no id for ${JSON.stringify(symbol)} and no <unk>`);
    return [unk];
  }
}

function splitOnce(merge: string): [string, string] {
  const at = merge.indexOf(" ");
  if (at < 0) throw new Error(`malformed merge entry ${JSON.stringify(merge)}`);
  return [merge.slice(0, at), merge.slice(at + 1)];
}
