import { applicableStillClasses, renditionLongEdge, type SizeClass } from "@starkeep/photos-ladder";
import { originalFacts, fetchPublishedRenditions } from "@/photos-lib/renditions/acquire";
import { loadRenditionsOf, loadHydratedRenditions } from "@/photos-lib/renditions/store";
import { loadAppCredentials, signedFetch } from "@starkeep/app-client";
import { precheckThumbnail } from "@/photos-lib";

/**
 * POST /api/resize — derive a record's renditions on the machine running this
 * server.
 *
 * The flow itself lives in `photos-lib`, shared with the cloud resize Lambda
 * and the local derivation worker; what is left here is the HTTP shape and the
 * two things only this node can supply — the platform HEIC decoder, and a
 * place on local disk to remember what it could not decode.
 *
 * `targetLongEdge` in the body narrows the work to the rung that answers that
 * many pixels, plus the ones the decode makes free. Omitting it means the whole
 * applicable ladder, which is what a bulk sweep wants and what a viewer waiting
 * on a tile very much does not.
 */
export async function POST(req: Request) {
  const creds = await loadAppCredentials("photos");
  if (!creds) {
    return Response.json(
      { error: "photos has not been installed locally — run install from admin-web first" },
      { status: 503 },
    );
  }

  const { targetId, targetLongEdge } = (await req.json()) as {
    targetId?: string;
    targetLongEdge?: number;
  };

  if (!targetId) {
    return Response.json({ error: "targetId is required" }, { status: 400 });
  }
  console.log(`[resize] start targetId=${targetId} appId=${creds.appId}`);

  const call = (path: string, init?: Parameters<typeof signedFetch>[2]) =>
    signedFetch(creds, path, init);

  const recordRes = await call(`/data/records/${targetId}`);
  if (!recordRes.ok) {
    const errBody = await recordRes.text().catch(() => "");
    console.error(`[resize] GET /data/records/${targetId} → ${recordRes.status}: ${errBody}`);
    return Response.json(
      { error: `Record fetch failed: ${recordRes.status} ${errBody}` },
      { status: recordRes.status === 404 ? 404 : 502 },
    );
  }
  const { record } = (await recordRes.json()) as {
    record: {
      id: string;
      type: string;
      object_storage_key: string | null;
      parent_id: string | null;
      mime_type: string | null;
      original_filename: string | null;
      metadata?: { width?: number; height?: number };
    };
  };

  if (!record.object_storage_key) {
    return Response.json({ error: "Record has no attached file" }, { status: 422 });
  }
  const mediaType = record.mime_type ?? record.type;
  if (mediaType.startsWith("video/")) {
    return Response.json(
      { error: "Video renditions are generated by the local library sweep" },
      { status: 422 },
    );
  }

  const facts = await originalFacts(call, targetId);
  if (facts?.availability?.state !== "instant") {
    const rows = await loadRenditionsOf(call, targetId);
    const sorted = rows.sort((a, b) => Math.max(a.width, a.height) - Math.max(b.width, b.height));
    const sourceLongEdge = Math.max(facts?.metadata?.width ?? 0, facts?.metadata?.height ?? 0);
    const applicable = sourceLongEdge > 0 ? applicableStillClasses(sourceLongEdge) : [];
    const spec = applicable.find(r => renditionLongEdge(r, sourceLongEdge) >= (targetLongEdge ?? 0)) ?? applicable.at(-1);
    const wanted = typeof targetLongEdge === "number"
      ? sorted.filter(r => spec ? r.size_class === spec.sizeClass : Math.max(r.width, r.height) === targetLongEdge)
      : sorted;
    const fetched = await fetchPublishedRenditions(call, wanted.map(r => r!.sub_key));
    return Response.json({ ok: true, published: [], fetched, declined: wanted.length === 0 });
  }

  // May this record be derived *from*? A rendition may not — that would
  // recurse. Any other child may: having a parent is not what makes a record a
  // rendition, and rejecting every record with a parent left such children with
  // no thumbnail and therefore invisible.
  const precheck = await precheckThumbnail(targetId, (p) => call(p));
  if (precheck.alreadyThumbnail) {
    return Response.json({ error: "Record is already a rendition" }, { status: 400 });
  }

  // Imported lazily so the route's bundle does not pull sharp in through a
  // static import graph.
  const { deriveAndPublish } = await import("@/photos-lib/image-processing/derive-and-publish");
  const { createSipsDecoder } = await import("@/photos-lib/image-processing/platform-decoder");
  const { fileAttemptStore } = await import("@/derivation/attempt-store");

  const here = (await loadHydratedRenditions(call, [targetId], { urls: false })).get(targetId) ?? [];
  const result = await deriveAndPublish({
    retainLocal: true,
    availableRenditionClasses: here.filter(r => r.availableHere).map(r => r.size_class as SizeClass),
    signedFetch: call,
    parent: {
      id: record.id,
      originalFilename: record.original_filename,
      mimeType: mediaType,
    },
    // Only called when there is work needing the bytes. The file-url endpoint
    // returns a self-signed token URL that needs no HMAC of its own.
    loadSource: async () => {
      const fileUrlRes = await call(`/data/records/${targetId}/file-url`);
      if (!fileUrlRes.ok) {
        throw new Error(`file-url failed: ${fileUrlRes.status}`);
      }
      const { url } = (await fileUrlRes.json()) as { url: string };
      const sourceRes = await fetch(url);
      if (!sourceRes.ok) throw new Error(`source fetch failed: ${sourceRes.status}`);
      return new Uint8Array(await sourceRes.arrayBuffer());
    },
    ...(typeof targetLongEdge === "number" ? { targetLongEdge } : {}),
    // The difference between the operator's primary capture format being
    // derivable on this machine or not. macOS ships a licensed HEVC decoder;
    // the prebuilt sharp does not.
    platformDecoder: createSipsDecoder(),
    attempts: fileAttemptStore(),
  });

  await fetchPublishedRenditions(call, []);

  if (result.outcome === "undecodable-here") {
    return Response.json(
      { error: "undecodable-here", detail: result.detail },
      { status: 422 },
    );
  }
  if (result.outcome === "publish-failed" || result.outcome === "transient-failure") {
    console.error(`[resize] ${result.detail}`);
    return Response.json(
      { ok: false, published: result.published, error: result.detail },
      { status: 502 },
    );
  }

  return Response.json({
    ok: true,
    published: result.published,
    archiveGate: result.archiveGate,
  });
}
