/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "starkeep-photos-api-starkeep": {
      "name": string
      "type": "sst.aws.Function"
    }
    "starkeep-photos-gateway-starkeep": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "starkeep-photos-web-starkeep": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}

import "sst"
export {}