import { type NextRequest, NextResponse } from "next/server";
import { loadAppCredentials, signedFetch } from "@starkeep/app-client";
import { precheckThumbnail } from "@/photos-lib";

export const runtime = "nodejs";

/**
 * POST /api/resize — derive a record's renditions on the machine running this
 * server.
 *
 * The flow itself lives in `photos-lib`, shared with the cloud resize Lambda
 * and the local derivation worker; what is left here is the HTTP shape and the
 * two things only this node can supply — the platform HEIC decoder, and a
 * place on local disk to remember what it could not decode.
 *
 * `targetLongEdge` in the body narrows the work to the rung that answers that
 * many pixels, plus the ones the decode makes free. Omitting it means the whole
 * applicable ladder, which is what a bulk sweep wants and what a viewer waiting
 * on a tile very much does not.
 */
export async function POST(req: NextRequest) {
  const creds = await loadAppCredentials("photos");
  if (!creds) {
    return NextResponse.json(
      { error: "photos has not been installed locally — run install from admin-web first" },
      { status: 503 },
    );
  }

  const { targetId, targetLongEdge } = (await req.json()) as {
    targetId?: string;
    targetLongEdge?: number;
  };

  if (!targetId) {
    return NextResponse.json({ error: "targetId is required" }, { status: 400 });
  }
  console.log(`[resize] start targetId=${targetId} appId=${creds.appId}`);

  const call = (path: string, init?: Parameters<typeof signedFetch>[2]) =>
    signedFetch(creds, path, init);

  const recordRes = await call(`/data/records/${targetId}`);
  if (!recordRes.ok) {
    const errBody = await recordRes.text().catch(() => "");
    console.error(`[resize] GET /data/records/${targetId} → ${recordRes.status}: ${errBody}`);
    return NextResponse.json(
      { error: `Record fetch failed: ${recordRes.status} ${errBody}` },
      { status: recordRes.status === 404 ? 404 : 502 },
    );
  }
  const { record } = (await recordRes.json()) as {
    record: {
      id: string;
      type: string;
      object_storage_key: string | null;
      parent_id: string | null;
      mime_type: string | null;
      original_filename: string | null;
    };
  };

  if (!record.object_storage_key) {
    return NextResponse.json({ error: "Record has no attached file" }, { status: 422 });
  }
  const mediaType = record.mime_type ?? record.type;
  if (mediaType.startsWith("video/")) {
    return NextResponse.json(
      { error: "Video renditions are generated by the local library sweep" },
      { status: 422 },
    );
  }

  // May this record be derived *from*? A rendition may not — that would
  // recurse. A crop may: it is a user artifact that needs its own tile, and
  // rejecting every record with a parent left crops with no thumbnail and
  // therefore invisible.
  const precheck = await precheckThumbnail(targetId, (p) => call(p));
  if (precheck.alreadyThumbnail) {
    return NextResponse.json({ error: "Record is already a rendition" }, { status: 400 });
  }

  // Imported lazily so the route's bundle does not pull sharp in through a
  // static import graph.
  const { deriveAndPublish } = await import("@/photos-lib/image-processing/derive-and-publish");
  const { createSipsDecoder } = await import("@/photos-lib/image-processing/platform-decoder");
  const { fileAttemptStore } = await import("@/derivation/attempt-store");

  const result = await deriveAndPublish({
    signedFetch: call,
    parent: {
      id: record.id,
      originalFilename: record.original_filename,
      mimeType: mediaType,
    },
    // Only called when there is work needing the bytes. The file-url endpoint
    // returns a self-signed token URL that needs no HMAC of its own.
    loadSource: async () => {
      const fileUrlRes = await call(`/data/records/${targetId}/file-url`);
      if (!fileUrlRes.ok) {
        throw new Error(`file-url failed: ${fileUrlRes.status}`);
      }
      const { url } = (await fileUrlRes.json()) as { url: string };
      const sourceRes = await fetch(url);
      if (!sourceRes.ok) throw new Error(`source fetch failed: ${sourceRes.status}`);
      return new Uint8Array(await sourceRes.arrayBuffer());
    },
    ...(typeof targetLongEdge === "number" ? { targetLongEdge } : {}),
    // The difference between the operator's primary capture format being
    // derivable on this machine or not. macOS ships a licensed HEVC decoder;
    // the prebuilt sharp does not.
    platformDecoder: createSipsDecoder(),
    attempts: fileAttemptStore(),
  });

  if (result.outcome === "undecodable-here") {
    return NextResponse.json(
      { error: "undecodable-here", detail: result.detail },
      { status: 422 },
    );
  }
  if (result.outcome === "publish-failed" || result.outcome === "transient-failure") {
    console.error(`[resize] ${result.detail}`);
    return NextResponse.json(
      { ok: false, published: result.published, error: result.detail },
      { status: 502 },
    );
  }

  return NextResponse.json({
    ok: true,
    published: result.published,
    archiveGate: result.archiveGate,
  });
}
